# Generated by Django 6.0.1 on 2026-01-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Party', 'Party Wear'), ('Daily', 'Daily Wear'), ('Cotton', 'Cotton Suits')], default='Daily', max_length=50),
        ),
    ]
